import { test, expect } from '../../helper/test';
import { TAGS, tags } from '../../helper/test-tags';
import { setJiraStory } from '../../helper/jira-story';
import { LoginPage } from '../../page-objects/auth/login-page';

/**
 * EXAMPLE — a spec generated by the qa-agent skill.
 *
 * Demonstrates the framework conventions:
 *   - import `test` + `expect` from `../../helper/test` (NOT from
 *     `@playwright/test`) so the failure → Jira-bug auto-fixture applies
 *   - `setJiraStory(...)` as the first line of the test body so any bug
 *     created on the final failed attempt is linked to the right user story
 *   - `tags(...)` (value == Jira label) for test selection
 *   - `test.step('...')` for a readable Allure / HTML report
 *
 * Auth runs once in global-setup; this test starts already-logged-in via
 * `use.storageState` in `playwright.config.ts`.
 */
test(
    'Login — a user can sign in with valid credentials',
    tags(TAGS.REGRESSION, TAGS.SMOKE, TAGS.P0),
    async ({ page }) => {
        setJiraStory('PROJ-1'); // ← parent user story key

        const loginPage = new LoginPage(page);

        await test.step('Open the sign-in page', async () => {
            await loginPage.open(process.env.AUTH_URL ?? '/signin');
        });

        await test.step('Sign in with a valid account', async () => {
            await loginPage.signIn(
                process.env.APP_USER ?? 'tester@example.com',
                process.env.APP_PASS ?? 'YOUR_PASSWORD'
            );
        });

        await test.step('Verify the user is signed in', async () => {
            await loginPage.verifySignedIn();
        });
    }
);
