/**
 * Write `test-output/ai/ci-summary.md` — a short summary suitable for
 * `$GITHUB_STEP_SUMMARY`, the Jenkins build description, or a GitLab CI
 * artifact preview.
 *
 * Deterministic. Reads `diagnosis.md` if present; otherwise builds from the
 * provided failure events directly.
 */

import fs from "node:fs";
import path from "node:path";

import { aiqaOutDir, ensureDir } from "../utils/paths";
import type { FailureEvent } from "../schemas/failure-event.schema";
import type { CriticalEvent } from "../watchers/critical-pattern-detector";

export interface CiSummaryInput {
    runId: string;
    failureEvents: FailureEvent[];
    criticals: CriticalEvent[];
    outDir?: string;
}

export function writeCiSummary(input: CiSummaryInput): string {
    const outDir = input.outDir ?? aiqaOutDir();
    ensureDir(outDir);

    const finals = input.failureEvents.filter(e => e.isFinalFailure);
    const lines: string[] = [];

    lines.push(`## AI QA Agent — run \`${input.runId}\``);
    lines.push("");
    if (finals.length === 0 && input.criticals.length === 0) {
        lines.push("✅ No final-attempt failures and no critical patterns detected.");
    } else {
        lines.push(`- **Final-attempt failures:** ${finals.length}`);
        lines.push(`- **Critical events:** ${input.criticals.length}`);
    }

    if (input.criticals.length > 0) {
        lines.push("");
        lines.push("### 🚨 Critical events");
        for (const c of input.criticals) {
            lines.push(`- \`${c.trigger}\` — ${c.summary}`);
        }
    }

    if (finals.length > 0) {
        lines.push("");
        lines.push("### Failing tests");
        for (const f of finals.slice(0, 20)) {
            lines.push(`- **${f.title}** — \`${f.file}\` — ${f.error.message || "no message"}`);
        }
        if (finals.length > 20) {
            lines.push(`- _…and ${finals.length - 20} more (see \`test-output/ai/diagnosis.md\`)_`);
        }
    }

    lines.push("");
    lines.push("_Generated by AI QA Agent (deterministic Phase 1; no LLM call)._");

    const filePath = path.join(outDir, "ci-summary.md");
    fs.writeFileSync(filePath, lines.join("\n"));
    return filePath;
}
