import { BasePage } from '../base-page';

/**
 * EXAMPLE — a page object generated by the qa-agent skill.
 *
 * Demonstrates the framework conventions:
 *   - `extends BasePage` (gives `this.page` and `this.actionKeyword`)
 *   - locators grouped in a private readonly object
 *   - every interaction through `this.actionKeyword.*` — never call
 *     `this.page.locator(...)` directly
 *   - prefer test-only attributes: data-zcqa → data-test-id → data-id →
 *     data-title (priority order honoured by ActionKeyword.healLocator)
 */
export class LoginPage extends BasePage {

    private readonly locators = {
        emailInput: '[data-test-id="email"]',
        passwordInput: '[data-test-id="password"]',
        submitButton: 'button[type="submit"]',
        errorBanner: '[data-test-id="login-error"]',
        avatar: '[data-test-id="user-avatar"]',
    };

    async open(url: string) {
        await this.actionKeyword.goto(url);
    }

    async signIn(email: string, password: string) {
        await this.actionKeyword.waitAndFill(this.locators.emailInput, email);
        await this.actionKeyword.waitAndFill(this.locators.passwordInput, password);
        await this.actionKeyword.waitAndClick(this.locators.submitButton);
    }

    async verifySignedIn() {
        await this.actionKeyword.verifyElementVisible(
            this.locators.avatar,
            'Expected the user avatar after a successful sign-in'
        );
    }

    async getErrorMessage(): Promise<string> {
        return this.actionKeyword.getElementText(this.locators.errorBanner);
    }
}
